"""initial_schema

Revision ID: fae71d516492
Revises: 
Create Date: 2026-09-24 13:18:49.648873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae71d516492'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('redirect_chain', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_domain'), 'scans', ['domain'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.create_table('domain_information',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domain_age_days', sa.Integer(), nullable=True),
    sa.Column('dnssec', sa.Boolean(), nullable=True),
    sa.Column('has_valid_ssl', sa.Boolean(), nullable=True),
    sa.Column('ssl_issuer', sa.String(length=255), nullable=True),
    sa.Column('nameservers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_information_scan_id'), 'domain_information', ['scan_id'], unique=True)
    op.create_table('fusion_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('raw_probability', sa.Float(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('modalities_used', sa.Text(), nullable=False),
    sa.Column('missing_modalities', sa.Text(), nullable=False),
    sa.Column('decision_policy_version', sa.String(length=50), nullable=False),
    sa.Column('calibration_version', sa.String(length=50), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('url_feature_hash', sa.String(length=64), nullable=True),
    sa.Column('dom_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('screenshot_hash', sa.String(length=64), nullable=True),
    sa.Column('model_input_hash', sa.String(length=64), nullable=True),
    sa.Column('prediction_hash', sa.String(length=64), nullable=True),
    sa.Column('live_content_changed', sa.Boolean(), nullable=True),
    sa.Column('content_change_notice', sa.Text(), nullable=True),
    sa.Column('reproducibility_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusion_analyses_scan_id'), 'fusion_analyses', ['scan_id'], unique=False)
    op.create_table('html_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('has_login_form', sa.Boolean(), nullable=True),
    sa.Column('external_form_action', sa.Boolean(), nullable=True),
    sa.Column('iframe_count', sa.Integer(), nullable=True),
    sa.Column('hidden_element_count', sa.Integer(), nullable=True),
    sa.Column('script_count', sa.Integer(), nullable=True),
    sa.Column('suspicious_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_html_features_scan_id'), 'html_features', ['scan_id'], unique=True)
    op.create_table('scan_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_evidence_provider'), 'scan_evidence', ['provider'], unique=False)
    op.create_index(op.f('ix_scan_evidence_scan_id'), 'scan_evidence', ['scan_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rule_match_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('feature_version', sa.String(length=50), nullable=True),
    sa.Column('preprocessing_version', sa.String(length=50), nullable=True),
    sa.Column('decision_policy_version', sa.String(length=50), nullable=True),
    sa.Column('url_feature_hash', sa.String(length=64), nullable=True),
    sa.Column('dom_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('screenshot_hash', sa.String(length=64), nullable=True),
    sa.Column('model_input_hash', sa.String(length=64), nullable=True),
    sa.Column('prediction_hash', sa.String(length=64), nullable=True),
    sa.Column('live_content_changed', sa.Boolean(), nullable=True),
    sa.Column('content_change_notice', sa.Text(), nullable=True),
    sa.Column('reproducibility_data', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_scan_id'), 'scan_results', ['scan_id'], unique=True)
    op.create_index(op.f('ix_scan_results_verdict'), 'scan_results', ['verdict'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('format_name', sa.String(length=20), nullable=False),
    sa.Column('md5_hash', sa.String(length=64), nullable=True),
    sa.Column('capture_duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_scan_id'), 'screenshots', ['scan_id'], unique=False)
    op.create_table('threat_indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_indicators_indicator_type'), 'threat_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_indicators_scan_id'), 'threat_indicators', ['scan_id'], unique=False)
    op.create_index(op.f('ix_threat_indicators_severity'), 'threat_indicators', ['severity'], unique=False)
    op.create_table('url_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('url_length', sa.Integer(), nullable=False),
    sa.Column('hostname_length', sa.Integer(), nullable=False),
    sa.Column('path_length', sa.Integer(), nullable=False),
    sa.Column('query_length', sa.Integer(), nullable=False),
    sa.Column('count_dots', sa.Integer(), nullable=False),
    sa.Column('count_hyphens', sa.Integer(), nullable=False),
    sa.Column('count_at', sa.Integer(), nullable=False),
    sa.Column('count_question_marks', sa.Integer(), nullable=False),
    sa.Column('count_equal_signs', sa.Integer(), nullable=False),
    sa.Column('count_subdomains', sa.Integer(), nullable=False),
    sa.Column('has_ip_address', sa.Boolean(), nullable=False),
    sa.Column('has_punycode', sa.Boolean(), nullable=False),
    sa.Column('has_shortener', sa.Boolean(), nullable=False),
    sa.Column('has_port_in_url', sa.Boolean(), nullable=False),
    sa.Column('entropy_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_features_scan_id'), 'url_features', ['scan_id'], unique=True)
    op.create_table('visual_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('dominant_colors', sa.String(length=255), nullable=True),
    sa.Column('brand_similarity_score', sa.Float(), nullable=True),
    sa.Column('detected_logos', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_analysis_scan_id'), 'visual_analysis', ['scan_id'], unique=True)
    op.create_table('website_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('initial_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('charset', sa.String(length=50), nullable=True),
    sa.Column('dom_depth', sa.Integer(), nullable=True),
    sa.Column('total_tags', sa.Integer(), nullable=True),
    sa.Column('text_ratio', sa.Float(), nullable=True),
    sa.Column('hidden_elements_count', sa.Integer(), nullable=True),
    sa.Column('total_forms', sa.Integer(), nullable=True),
    sa.Column('login_forms_count', sa.Integer(), nullable=True),
    sa.Column('has_password_field', sa.Boolean(), nullable=True),
    sa.Column('external_form_action_count', sa.Integer(), nullable=True),
    sa.Column('total_links', sa.Integer(), nullable=True),
    sa.Column('internal_links', sa.Integer(), nullable=True),
    sa.Column('external_links', sa.Integer(), nullable=True),
    sa.Column('external_link_ratio', sa.Float(), nullable=True),
    sa.Column('null_link_ratio', sa.Float(), nullable=True),
    sa.Column('total_scripts', sa.Integer(), nullable=True),
    sa.Column('inline_scripts', sa.Integer(), nullable=True),
    sa.Column('external_scripts', sa.Integer(), nullable=True),
    sa.Column('total_iframes', sa.Integer(), nullable=True),
    sa.Column('hidden_iframes', sa.Integer(), nullable=True),
    sa.Column('cross_origin_iframes', sa.Integer(), nullable=True),
    sa.Column('total_resources', sa.Integer(), nullable=True),
    sa.Column('external_resource_ratio', sa.Float(), nullable=True),
    sa.Column('mixed_content_count', sa.Integer(), nullable=True),
    sa.Column('hsts_present', sa.Boolean(), nullable=True),
    sa.Column('csp_present', sa.Boolean(), nullable=True),
    sa.Column('x_frame_options', sa.String(length=50), nullable=True),
    sa.Column('x_content_type_options', sa.String(length=50), nullable=True),
    sa.Column('security_header_score', sa.Float(), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_analyses_scan_id'), 'website_analyses', ['scan_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fusion_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_signals', sa.Text(), nullable=False),
    sa.Column('observed_evidence', sa.Text(), nullable=False),
    sa.Column('feature_attributions', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fusion_analysis_id'], ['fusion_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_fusion_analysis_id'), 'explanations', ['fusion_analysis_id'], unique=False)
    op.create_table('model_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fusion_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['fusion_analysis_id'], ['fusion_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_executions_fusion_analysis_id'), 'model_executions', ['fusion_analysis_id'], unique=False)
    op.create_table('visual_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('screenshot_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('preprocessing_version', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('phishing_probability', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('inference_latency_ms', sa.Float(), nullable=False),
    sa.Column('has_centered_card', sa.Boolean(), nullable=False),
    sa.Column('edge_density', sa.Float(), nullable=True),
    sa.Column('whitespace_ratio', sa.Float(), nullable=True),
    sa.Column('dominant_colors', sa.Text(), nullable=True),
    sa.Column('heatmap_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_analyses_scan_id'), 'visual_analyses', ['scan_id'], unique=False)
    op.create_index(op.f('ix_visual_analyses_screenshot_id'), 'visual_analyses', ['screenshot_id'], unique=False)
    op.create_table('website_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('website_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['website_analysis_id'], ['website_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_evidence_website_analysis_id'), 'website_evidence', ['website_analysis_id'], unique=False)
    op.create_table('website_redirect_hops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('website_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('hop_number', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['website_analysis_id'], ['website_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_redirect_hops_website_analysis_id'), 'website_redirect_hops', ['website_analysis_id'], unique=False)
    op.create_table('visual_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visual_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['visual_analysis_id'], ['visual_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_evidence_visual_analysis_id'), 'visual_evidence', ['visual_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_evidence_visual_analysis_id'), table_name='visual_evidence')
    op.drop_table('visual_evidence')
    op.drop_index(op.f('ix_website_redirect_hops_website_analysis_id'), table_name='website_redirect_hops')
    op.drop_table('website_redirect_hops')
    op.drop_index(op.f('ix_website_evidence_website_analysis_id'), table_name='website_evidence')
    op.drop_table('website_evidence')
    op.drop_index(op.f('ix_visual_analyses_screenshot_id'), table_name='visual_analyses')
    op.drop_index(op.f('ix_visual_analyses_scan_id'), table_name='visual_analyses')
    op.drop_table('visual_analyses')
    op.drop_index(op.f('ix_model_executions_fusion_analysis_id'), table_name='model_executions')
    op.drop_table('model_executions')
    op.drop_index(op.f('ix_explanations_fusion_analysis_id'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_website_analyses_scan_id'), table_name='website_analyses')
    op.drop_table('website_analyses')
    op.drop_index(op.f('ix_visual_analysis_scan_id'), table_name='visual_analysis')
    op.drop_table('visual_analysis')
    op.drop_index(op.f('ix_url_features_scan_id'), table_name='url_features')
    op.drop_table('url_features')
    op.drop_index(op.f('ix_threat_indicators_severity'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_scan_id'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_indicator_type'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    op.drop_index(op.f('ix_screenshots_scan_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_scan_results_verdict'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_scan_evidence_scan_id'), table_name='scan_evidence')
    op.drop_index(op.f('ix_scan_evidence_provider'), table_name='scan_evidence')
    op.drop_table('scan_evidence')
    op.drop_index(op.f('ix_html_features_scan_id'), table_name='html_features')
    op.drop_table('html_features')
    op.drop_index(op.f('ix_fusion_analyses_scan_id'), table_name='fusion_analyses')
    op.drop_table('fusion_analyses')
    op.drop_index(op.f('ix_domain_information_scan_id'), table_name='domain_information')
    op.drop_table('domain_information')
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_domain'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
